model:
  context_length: 128
  d_model: 256
  num_heads: 8
  num_layers: 4
  ff_dim: 512
  dropout: 0.1

data:
  path: "./data"
  stride: 1
  num_workers: 4

training:
  batch_size: 32
  num_epochs: 5
  learning_rate: 0.0001
  use_scheduler: False
