model:
  context_length: 128
  d_model: 128
  num_heads: 4
  num_layers: 4
  ff_dim: 256
  dropout: 0.1

data:
  path: "./data"
  stride: 1
  num_workers: 4

training:
  batch_size: 32
  num_epochs: 20
  learning_rate: 0.0001
  use_scheduler: False
